services:
    club_extra.paginator:
        class: Club\ExtraBundle\Helper\Paginator
        arguments: [50, 7, @router]
    club_extra.breadcrumb:
        class: Club\ExtraBundle\Helper\Breadcrumb
    club_extra.google_geocode:
        class: Club\ExtraBundle\Helper\GoogleGeocode
        arguments: [@service_container]
