services:
    club_extra.twig_breadcrumb:
        class: Club\ExtraBundle\Twig\BreadcrumbExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }
    club_extra.twig_paginator:
        class: Club\ExtraBundle\Twig\PaginatorExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }
    club.socialBarHelper:
        class : Club\ExtraBundle\Helper\SocialBarHelper
        tags : 
            - {name : 'templating.helper', alias : 'social-buttons'} 
        arguments : [@templating]
    twig.extension.club_social_bar:
        class: Club\ExtraBundle\Twig\SocialBar
        tags:
            - { name: 'twig.extension' }
        arguments : [@service_container]
