services:
    club_extra.twig_breadcrumb:
        class: Club\ExtraBundle\Twig\BreadcrumbExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }
    club_extra.twig_paginator:
        class: Club\ExtraBundle\Twig\PaginatorExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }
    club.socialBarHelper:
        class : Club\ExtraBundle\Helper\SocialBarHelper
        arguments : [@templating]
        tags :
            - { name: 'templating.helper', alias: 'social-buttons' }
    twig.extension.club_social_bar:
        class: Club\ExtraBundle\Twig\SocialBar
        arguments : [@service_container]
        tags:
            - { name: 'twig.extension' }
    twig.extension.club_google_map:
        class: Club\ExtraBundle\Twig\GoogleMapExtension
        arguments : [@service_container]
        tags:
            - { name: 'twig.extension' }
