services:
    club_extra.twig_breadcrumb:
        class: Club\ExtraBundle\Twig\BreadcrumbExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }
    club_extra.twig_paginator:
        class: Club\ExtraBundle\Twig\PaginatorExtension
        arguments: [@service_container]
        tags:
            - { name: twig.extension }
